### ISSUE TITLE
Join query with objectID in Mongo document _ID

### ISSUE THREAD

**Issue by luongdq** [siddhi-io/siddhi-store-mongodb#58] opened 2020-12-17 02:29 UTC
I've tried to get the whole document related to the update event by using a join query with objectID but it's not success:

from UpdateStream as u left outer join stocks as s on u.id == s.id
select u.id as id, s.name as name, s.volume as volume, s.stockDetails as stockDetails
insert into LogInsertUpdateStream;

The above query result is alway null.
My question is how to to retrieve the whole document using the document id in join query ?
Thank you

**Comment by FazlanFarook** [comment] 2020-12-23 11:20
@luongdq  I also facing the same problem, Did you able to fix this, or did you get any update?

**Comment by luongdq** [comment] 2020-12-23 11:50
I've not fixed it yet, but I've found a workaround. As my store destination table is mysql, so I join updatestream with mysql table and use ifThenElse function to get not null data.

from UpdateStream as u left outer join mysql_stock as m on u.id == m.id
select u.id as id, ifThenElse(u.name is null, m.name, u.name) as name, ifThenElse(u.volume is null, m.volume, u.volume) as volume, ifThenElse(u.stockDetails is null, m.stockdetails, u.stockDetails) as stockDetails
insert into LogUpdateStream;

**Comment by FazlanFarook** [comment] 2020-12-23 11:59
@luongdq thank you brother, this won't help my case. I have to update some fields with null values too from the stream.

**Comment by niveathika** [comment] 2020-12-24 16:18
@luongdq & @FazlanFarook The column names in the siddhi store is mapped exactly to the MongoDB document field. The above may be expecting a new field called "id" and not the identifying column that you both are trying to query. Have you tried defining the field as "_id"?

If that is not working we have to debug and check the why the match filter is not applying properly in the query we execute on the DB.
https://github.com/siddhi-io/siddhi-store-mongodb/blob/master/component/src/main/java/io/siddhi/extension/store/mongodb/MongoDBEventTable.java#L644

**Comment by FazlanFarook** [comment] 2020-12-24 16:46
@niveathika Thank you for the reply, I have tried with "_id" too, but didn't work. can you provide me an example of a siddhi update file?

**Comment by FazlanFarook** [comment] 2020-12-24 16:53
@niveathika FYI I can join other fields and get the data, the only problem with "_id" join

**Comment by niveathika** [comment] 2020-12-24 17:00
Seems as per MongoDB docs, we cant use simple string match for "_id" field as this needs to be wrapped in an object. As of now, this is not handled in MongoDB store and we need to improve it to support this.

[1] https://docs.mongodb.com/manual/reference/method/ObjectId/

**Comment by FazlanFarook** [comment] 2020-12-26 12:52
@niveathika Thank you for your information,

**Comment by luongdq** [comment] 2020-12-29 02:24
@niveathika Thank you for information, do you think we can improve json extension to add a function that convert string to objectID.

**Comment by niveathika** [comment] 2021-01-03 06:01
@sajithshn @tishan89 Your thoughts on this?
IMO this would be easier if we have an execution extension which can create & read objectID Java objects which can then passed through with Siddhi object datatype

**Comment by tishan89** [comment] 2021-01-03 13:18
Why can't we handle it at the mongo extension. ie. Add string representation of objectId into Siddhi event using [valueOf()](https://docs.mongodb.com/manual/reference/method/ObjectId.valueOf/#ObjectId.valueOf)

**Comment by FazlanFarook** [comment] 2021-01-03 13:41
@tishan89 I have already captured the value of object id in a string from cdc stream. But we cannot able to join that string with mongodb store using _id since mongodb itself contain _id as ObjectId.

**Comment by tishan89** [comment] 2021-01-03 13:57
Yeah. What I am suggesting is to set string value of ObjectId to _id rather than the java object itself. @niveathika do you see any issues with that when compared with the execution extension approach

**Comment by FazlanFarook** [comment] 2021-01-03 14:03
@tishan89 You mean in the db itself? I tried with that too. After changed to the ObjectId to string the db level the cdc didn't work since for the _id it is looking for the ObjectId.

**Comment by niveathika** [comment] 2021-01-03 14:05
> Yeah. What I am suggesting is to set the string value of ObjectId to _id rather than the java object itself. @niveathika do you see any issues with that when compared with the execution extension approach

The issue is we cant set the string value since MongoDB only allows Java objects when filtering based on "_id" field. This needs to be special-cased in the MongoDB extension when processing the condition.

**Comment by dnwick** [comment] 2021-01-07 12:29
This is fixed in master for on conditions. We will do a release soon once we finalize all the cases.

**Comment by dnwick** [comment] 2021-04-02 15:53
Fixed with https://github.com/siddhi-io/siddhi-store-mongodb/pull/59

**Closed as completed by dnwick** 2021-04-02 15:53 UTC
